version: "3.8"
services:
  web:
    image: "docker.io/library/vaadin-builder-demo:1.0-SNAPSHOT"
    ports:
      - "8080:8080"
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vaadin'
    depends_on:
      - db
#    networks:
#      - app-network
  db:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    volumes:
      - 'db_data:/bitnami/postgresql'
    environment:
      - 'POSTGRESQL_DATABASE=vaadin'
      - 'POSTGRESQL_USERNAME=vaadin'
      - 'POSTGRESQL_PASSWORD=vaadin'
#    networks:
#      - app-network
volumes:
   db_data:
     driver: local
#networks:
#  local:
#    driver: bridge